---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bosh-cpi-manager
  namespace: bosh
rules:
- apiGroups: ["", "extensions"]
  resources: ["pods", "configmaps", "services", "persistentvolumeclaims"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bosh-cpi-binding
  namespace: bosh
subjects:
- kind: ServiceAccount
  name: default
  namespace: bosh
roleRef:
  kind: Role
  name: bosh-cpi-manager
  apiGroup: rbac.authorization.k8s.io
